### ISSUE TITLE
Set default config values by configuration file

### ISSUE THREAD

**Issue by tmrowe** [ministryofjustice/apvs-internal-web#150]
At present when the IntSchema.AutoApprovalConfig table is constructed a row is added to the table in the migration script that sets the default configuration values. 

If no rows are present in the table it is impossible to load the config page without seeing an error. The only way to resolve this error is to then rollback the database and rerun the migration scripts or to manually insert a config row.

We should instead set default values in our configuration file and simple have the defaults overwritten if their is a row in the IntSchema.AutoApprovalConfig table that is enabled. This will make our default configuration more explicit and easily configured, and remove an error case.

**Comment by pwright08** [comment]
Default value for `Max number of claims per month` is still not showing on dev environment

![screen shot 2017-01-20 at 15 09 19](https://cloud.githubusercontent.com/assets/9826034/22154205/8349ffc6-df22-11e6-904d-26d523e06cca.png)

**Comment by pwright08** [comment]
Above issue was a result of old data. Updated on dev and test now.
