### ISSUE TITLE
Cannot preview sum of accepted amount before making decision

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-internal-web#159]
If a caseworker selects to approve a different amount, we don't currently display a preview of the approved amount, but only the Total Expense Cost requested.

Probably need some front end javascript to work out the current approved amount.

Solution may look like:

![screen shot 2017-01-06 at 12 38 02](https://cloud.githubusercontent.com/assets/9826034/21718278/5850feba-d40e-11e6-8cc7-d82a4d77f855.png)

**Comment by hvekriya** [comment]
fixed by #172
