### ISSUE TITLE
Able to approve claim with all claim expenses rejected

### ISSUE THREAD

**Issue by msjhall138** [ministryofjustice/apvs-internal-web#189]
You can currently approve a claim with all claim expense items rejected

Need to add check to make sure at least 1 expense is approved/approved diff amount before it can be closed

Display an error message if all expenses are rejected and the caseworker tries to approve the claim. 

Internal
![screencapture-localhost-3001-claim-119-1484221170315](https://cloud.githubusercontent.com/assets/5646670/21888385/f4fed852-d8bb-11e6-8bd5-84121581d5f5.png)

External
![screen shot 2017-01-12 at 11 43 42](https://cloud.githubusercontent.com/assets/5646670/21888500/766ba76c-d8bc-11e6-8f61-142a3f4b691d.png)

**Comment by tmrowe** [comment]
Agreed with Chris that we should add a check on the expenses that should cause an error message to be displayed if all expenses where rejected. This check should be in addition to any existing checks. This would mean any claim with all rejected expenses must be rejected.

**Comment by hvekriya** [comment]
closed by #189
