### ISSUE TITLE
Request information in dashboard and advance search

### ISSUE THREAD

**Issue by msjhall138** [ministryofjustice/apvs-internal-web#193]
Currently in the options for the dashboard and the advance search none return any value for when the status of a claim is Request Information. Should this be included in the queries for In Progress, or does this need its own value?

![screen shot 2017-01-13 at 10 14 56](https://cloud.githubusercontent.com/assets/5646670/21926352/4d78d5e2-d979-11e6-83d7-77804bd5d6d0.png)
![screen shot 2017-01-13 at 10 14 43](https://cloud.githubusercontent.com/assets/5646670/21926351/4d7821b0-d979-11e6-9506-4bbd646f91f4.png)

**Comment by hvekriya** [comment]
I think request information should fall under in-progress as that claim is already been reviewed
