### ISSUE TITLE
Should the total approved cost also consider any deductions?

### ISSUE THREAD

**Issue by hvekriya** [ministryofjustice/apvs-internal-web#220]
At the moment the total approved cost does not consider any deductions.

<img width="967" alt="screen shot 2017-01-17 at 17 17 45" src="https://cloud.githubusercontent.com/assets/11596078/22031685/4a850ba4-dcd9-11e6-8340-b89cba043eb0.png">

In this case should the total approved cost be £20 - £3.40?

**Comment by pwright08** [comment]
Yes it should consider deductions

**Comment by stevenalexander** [comment]
verified
