### ISSUE TITLE
Overpayment currency displays decimals incorrectly for amount

### ISSUE THREAD

**Issue by msjhall138** [ministryofjustice/apvs-internal-web#239]
Needs to be made to show 2 decimals if there are any, if not then show no decimals

![screen shot 2017-01-25 at 11 27 05](https://cloud.githubusercontent.com/assets/5646670/22289012/58cb7aea-e2f1-11e6-91c5-33376386a250.png)

**Comment by gdouglas1** [comment]
Noticed that the OVERPAID-CLAIM-UPDATE claim event has the same issue.

To be done:
- [ ] Fix display issue on overpayment warning at top of view-claim page
- [ ] Format overpayment amounts in OVERPAID-CLAIM-UPDATE claim event
