### ISSUE TITLE
Claim decision selections and inputs are lost when a deduction is made

### ISSUE THREAD

**Issue by pwright08** [ministryofjustice/apvs-internal-web#247]
To reproduce:

1. Go to the view claim page to process a new claim
2. Select claim decisions using the drop-down boxes for the benefits, visit confirmation, expenses, etc.
3. Enter an approved different amount for an expense
4. Add an HC3 deduction
5. The page reloads and the previous decisions/amounts that were input are lost

A similar issue occurs when the user goes to the upload page, tracked in #75.

**Comment by stevenalexander** [comment]
Want to check with Caseworkers if this is an issue first.
