### ISSUE TITLE
Cannot reject a claim when rejecting all expenses

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-internal-web#250]
When I attempt to reject a claim and reject all the expenses I get a validation error "At least one expense must not be rejected for the claim to be approved".

Steps:
1. Submit a claim with a single expense
2. In internal view claim, select reject for all dropdowns (including expense) and reject the claim

Expected behaviour:
You should be able to reject a claim and reject all expenses. This validation should only apply when approving a claim.

Environment: local

![screen shot 2017-01-26 at 11 43 53](https://cloud.githubusercontent.com/assets/1783543/22330233/2f093af4-e3bd-11e6-856a-0eaa517ab3ad.png)

**Comment by hvekriya** [comment]
Verified. Closing the issue. Bug fixed by #253

**Comment by hvekriya** [comment]
Verified. Closing the issue. Bug fixed by #253
