### ISSUE TITLE
Advanced search link on normal search results page

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-internal-web#259]
Currently when you perform a normal search, the advanced search link disappears when the results appear.

It is likely a user would want to perform an advanced search if their normal search doesn't find what they want.
![screen shot 2017-01-27 at 15 27 41](https://cloud.githubusercontent.com/assets/1783543/22376419/c25d2f7a-e4a5-11e6-8b05-07d51fc9e9e9.png)

**Comment by msjhall138** [comment]
On test and working
