### ISSUE TITLE
IE8 issue when approving a claim

### ISSUE THREAD

**Issue by stevenalexander** [ministryofjustice/apvs-internal-web#37]
Saucelab test is failing at the point you select your response (Approve/Reject etc.).

https://saucelabs.com/tests/1aa361580dfc4a3683c19ad9761d2fc7

**Comment by gdouglas1** [comment]
Seems to be an issue with the Javascript that shows the panel when you select the Approve radio button.

**Comment by gdouglas1** [comment]
Not fixing this one as internal users will be using Firefox.  No users should be using IE8 on the internal site.
